using System;
using System.Linq;

using Mathematics.Lists;

namespace ProjectEuler.Problems
{
    /// <summary>
    /// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
    ///
    ///                1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    ///
    ///By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
    /// </summary>
	class Exercise2
	{
		public static Object Solve()
		{
			var solution = FibonacciSequence.Items.TakeWhile(x => x <= 4000000)
													 .Where(x => x%2 == 0)
													 .Sum();
            return solution;
		}
	}
}
